/*

 GENERALTILES_MAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : generalTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __generalTiles_map3_h_INCLUDE
#define __generalTiles_map3_h_INCLUDE

#define generalTiles_Map3Width 20
#define generalTiles_Map3Height 18
#define generalTiles_Map3Bank 0

extern const unsigned char generalTiles_Map3[];

#endif

/* End of GENERALTILES_MAP3.H */
