/*

 GENERALTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 14

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __generalTiles_h_INCLUDE
#define __generalTiles_h_INCLUDE

/* Bank of tiles. */
#define generalTilesBank 0
/* Start of tile array. */
extern const unsigned char generalTiles[];

#endif

/* End of GENERALTILES.H */
