/*

 GENERALTILES_MAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : generalTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __generalTiles_map2_h_INCLUDE
#define __generalTiles_map2_h_INCLUDE

#define generalTiles_Map2Width 20
#define generalTiles_Map2Height 18
#define generalTiles_Map2Bank 0

extern const unsigned char generalTiles_Map2[];

#endif

/* End of GENERALTILES_MAP2.H */
