/*

 GENERALTILESOUTRO_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : generalTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __generalTilesOutro_map_h_INCLUDE
#define __generalTilesOutro_map_h_INCLUDE

#define generalTilesOutro_MapWidth 20
#define generalTilesOutro_MapHeight 18
#define generalTilesOutro_MapBank 0

extern const unsigned char generalTilesOutro_Map[];

#endif

/* End of GENERALTILESOUTRO_MAP.H */
