/*

 INTROTILES_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : introTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __introTiles_Map_h_INCLUDE
#define __introTiles_Map_h_INCLUDE

#define introTiles_MapWidth 20
#define introTiles_MapHeight 18
#define introTiles_MapBank 0

extern const unsigned char introTiles_Map[];

#endif

/* End of INTROTILES_MAP.H */
