/*

 MENUTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 97

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __menuTiles_h_INCLUDE
#define __menuTiles_h_INCLUDE

/* Bank of tiles. */
#define menuTilesBank 0

/* Super Gameboy palette 0 */
#define menuTilesSGBPal0c0 0
#define menuTilesSGBPal0c1 0
#define menuTilesSGBPal0c2 0
#define menuTilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define menuTilesSGBPal1c0 6076
#define menuTilesSGBPal1c1 8935
#define menuTilesSGBPal1c2 6596
#define menuTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define menuTilesSGBPal2c0 6076
#define menuTilesSGBPal2c1 8935
#define menuTilesSGBPal2c2 6596
#define menuTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define menuTilesSGBPal3c0 6076
#define menuTilesSGBPal3c1 8935
#define menuTilesSGBPal3c2 6596
#define menuTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define menuTilesCGBPal0c0 0
#define menuTilesCGBPal0c1 32767
#define menuTilesCGBPal0c2 15855
#define menuTilesCGBPal0c3 28575

/* Gameboy Color palette 1 */
#define menuTilesCGBPal1c0 6076
#define menuTilesCGBPal1c1 8935
#define menuTilesCGBPal1c2 6596
#define menuTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define menuTilesCGBPal2c0 6076
#define menuTilesCGBPal2c1 8935
#define menuTilesCGBPal2c2 6596
#define menuTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define menuTilesCGBPal3c0 6076
#define menuTilesCGBPal3c1 8935
#define menuTilesCGBPal3c2 6596
#define menuTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define menuTilesCGBPal4c0 6076
#define menuTilesCGBPal4c1 8935
#define menuTilesCGBPal4c2 6596
#define menuTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define menuTilesCGBPal5c0 6076
#define menuTilesCGBPal5c1 8935
#define menuTilesCGBPal5c2 6596
#define menuTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define menuTilesCGBPal6c0 6076
#define menuTilesCGBPal6c1 8935
#define menuTilesCGBPal6c2 6596
#define menuTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define menuTilesCGBPal7c0 6076
#define menuTilesCGBPal7c1 8935
#define menuTilesCGBPal7c2 6596
#define menuTilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char menuTiles[];

#endif

/* End of MENUTILES.H */
