/*

 MENUTILES_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : menuTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __menuTiles_Map_h_INCLUDE
#define __menuTiles_Map_h_INCLUDE

#define menuTiles_MapWidth 20
#define menuTiles_MapHeight 18
#define menuTiles_MapBank 0

#define menuTiles_Map menuTiles_MapPLN0
extern const unsigned char menuTiles_MapPLN0[];

#endif

/* End of MENUTILES_MAP.H */
