/*

 OVERLAYMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 6
   Tile set      : generalTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __overlayMap_h_INCLUDE
#define __overlayMap_h_INCLUDE

#define overlayMapWidth 20
#define overlayMapHeight 6
#define overlayMapBank 0

extern const unsigned char overlayMap[];

#endif

/* End of OVERLAYMAP.H */
