/*

 OVERLAY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 3
   Tile set      : generalTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __overlay_h_INCLUDE
#define __overlay_h_INCLUDE

#define overlayWidth 20
#define overlayHeight 3
#define overlayBank 0

extern const unsigned char overlay[];

#endif

/* End of OVERLAY.H */
