/*

 SCORETILES_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : introTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __scoreTiles_Map_h_INCLUDE
#define __scoreTiles_Map_h_INCLUDE

#define scoreTiles_MapWidth 20
#define scoreTiles_MapHeight 18
#define scoreTiles_MapBank 0

extern const unsigned char scoreTiles_Map[];

#endif

/* End of SCORETILES_MAP.H */
